//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamToEarn.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ad
    {
        public int Id { get; set; }
        public string adURL { get; set; }
        public Nullable<System.DateTime> addeddate { get; set; }
    }
}
