//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamToEarn.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commission
    {
        public int ComId { get; set; }
        public int planId { get; set; }
        public int UserId { get; set; }
        public Nullable<decimal> TotalCommission { get; set; }
        public Nullable<System.DateTime> ComDate { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> CommissionPercentage { get; set; }
    }
}
