//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamToEarn.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrawsDay
    {
        public int Id { get; set; }
        public Nullable<int> FirstDay { get; set; }
        public Nullable<int> SecondDay { get; set; }
        public Nullable<int> ThirdDay { get; set; }
        public Nullable<int> ForthDay { get; set; }
    }
}
