//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamToEarn.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrawAmount
    {
        public int drawId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> totalDraw { get; set; }
        public Nullable<decimal> totalEarningOnDraw { get; set; }
        public Nullable<System.DateTime> drawDate { get; set; }
        public string OTPTokens { get; set; }
        public Nullable<bool> drawStatus { get; set; }
        public Nullable<bool> isAdminApprove { get; set; }
        public Nullable<decimal> Deductions { get; set; }
        public Nullable<bool> drawSentByExchanger { get; set; }
        public string DrawType { get; set; }
        public Nullable<System.DateTime> DrawSentDate { get; set; }
    }
}
