//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamToEarn.DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DreamToEarnEntities1 : DbContext
    {
        public DreamToEarnEntities1()
            : base("name=DreamToEarnEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ad> ads { get; set; }
        public virtual DbSet<Commission> Commissions { get; set; }
        public virtual DbSet<DrawAmount> DrawAmounts { get; set; }
        public virtual DbSet<DrawsDay> DrawsDays { get; set; }
        public virtual DbSet<EarningTranfer> EarningTranfers { get; set; }
        public virtual DbSet<InvestmentPlan> InvestmentPlans { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersAd> UsersAds { get; set; }
        public virtual DbSet<CommReferrer> CommReferrers { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<UsersCommission> UsersCommissions { get; set; }
        public virtual DbSet<UsersDetail> UsersDetails { get; set; }
        public virtual DbSet<UsersWithdraw> UsersWithdraws { get; set; }
    }
}
