//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamToEarn.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EarningTranfer
    {
        public int TransferId { get; set; }
        public string TransferAmount { get; set; }
        public int TranferByUserId { get; set; }
        public int TransFerToUserId { get; set; }
        public string TotalEarningOnTransfer { get; set; }
        public System.DateTime TransferDate { get; set; }
        public string Comments { get; set; }
        public string TransactionToken { get; set; }
    }
}
