//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamToEarn.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestmentPlan
    {
        public int planId { get; set; }
        public string plan { get; set; }
        public string planType { get; set; }
        public Nullable<System.DateTime> planAddDate { get; set; }
        public Nullable<System.DateTime> planActiveDate { get; set; }
        public string planStatus { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> TotalEarnings { get; set; }
        public Nullable<int> InvestPercentage { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> Commission { get; set; }
    
        public virtual InvestmentPlan InvestmentPlan1 { get; set; }
        public virtual InvestmentPlan InvestmentPlan2 { get; set; }
    }
}
