//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamToEarn.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersCommission
    {
        public int ComId { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> TotalCommission { get; set; }
        public string CommissionOnPlan { get; set; }
        public Nullable<System.DateTime> ComDate { get; set; }
        public int CommissionPercentage { get; set; }
        public bool IsApproved { get; set; }
    }
}
