//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamToEarn.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersDetail
    {
        public int planId { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<int> RefUserId { get; set; }
        public Nullable<int> Role { get; set; }
        public string plan { get; set; }
        public string planType { get; set; }
        public Nullable<System.DateTime> planAddDate { get; set; }
        public Nullable<System.DateTime> planActiveDate { get; set; }
        public string planStatus { get; set; }
        public decimal TotalEarnings { get; set; }
        public int InvestPercentage { get; set; }
        public string TransactionToken { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ReferencedBy { get; set; }
        public Nullable<decimal> TotalCommissionsx { get; set; }
    }
}
