//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamToEarn.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAd
    {
        public int Id { get; set; }
        public int adId { get; set; }
        public Nullable<bool> IsViewed { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> forDate { get; set; }
    }
}
